_target_: main.Main

proj_name: fff_butbetter
run_name: null

defaults:
  - _self_
  - exp: train
  - optim: adam
  - loader: mnist
  - model: fff
  - mlflow
  # you can add - slurm or - pbs

epochs: 50
seed: 47
debug_level: 0 # 0: no debug, 1: mlflow debug, 2:mlflow half debug 3:full debug

device: 
  _target_: torch.device
  type: cuda
  index: 0

## Output dir
hydra:
  run:
    dir: data/${proj_name}_debug${debug_level}_outputs/${exp._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: data/${proj_name}_debug${debug_level}_multirun/${exp._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job: # squeue
    name: ${proj_name}_${exp._target_}
